# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Use whatever you want for string literals
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes
  Include:
    - "app/**/*"
    - "config/**/*"
    - "lib/**/*"
    - "test/**/*"
    - "Gemfile"
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
